Update compile_and_evaluate.yml

diff --git a/.github/workflows/compile_and_evaluate.yml b/.github/workflows/compile_and_evaluate.yml
--- a/.github/workflows/compile_and_evaluate.yml
+++ b/.github/workflows/compile_and_evaluate.yml
@@ -27,20 +27,26 @@ jobs:
           echo "Running $sheet"
           if [ -d "$sheet/Submissions" ]; then
             echo "Submissions directory found in $sheet"
-            for file in "$sheet/Submissions"/*.cpp; do
-              if [ -f "$file" ]; then
-                dir=$(dirname "$file")
-                echo "Compiling $file"
-                g++ -o "${file%.cpp}" "$file"
-                if [ $? -eq 0 ]; then
-                  echo "Running ${file%.cpp}"
-                  result=$(/usr/bin/time -v ./"${file%.cpp}" 2>&1)
-                  echo "$result" > "${dir}/README.md"
-                else
-                  echo "Compilation failed for $file" > "${dir}/README.md"
-                fi
+            for subdir in "$sheet/Submissions"/*; do
+              if [ -d "$subdir" ]; then
+                echo "Processing $subdir"
+                for file in "$subdir"/*.cpp; do
+                  if [ -f "$file" ]; then
+                    echo "Compiling $file"
+                    g++ -o "${file%.cpp}" "$file"
+                    if [ $? -eq 0 ]; then
+                      echo "Running ${file%.cpp}"
+                      result=$(/usr/bin/time -v ./"${file%.cpp}" 2>&1)
+                      echo "$result" > "${subdir}/README.md"
+                    else
+                      echo "Compilation failed for $file" > "${subdir}/README.md"
+                    fi
+                  else
+                    echo "No .cpp files found in $subdir"
+                  fi
+                done
               else
-                echo "No .cpp files found in $sheet/Submissions"
+                echo "$subdir is not a directory"
               fi
             done
           else
