Update compile_and_evaluate.yml

diff --git a/.github/workflows/compile_and_evaluate.yml b/.github/workflows/compile_and_evaluate.yml
--- a/.github/workflows/compile_and_evaluate.yml
+++ b/.github/workflows/compile_and_evaluate.yml
@@ -23,17 +23,23 @@ jobs:
         for sheet in Sheet*; do
           if [ -d "$sheet/Submissions" ]; then
             for file in "$sheet/Submissions"/*.cpp; do
-              dir=$(dirname "$file")
-              echo "Compiling $file"
-              g++ -o "${file%.cpp}" "$file"
-              if [ $? -eq 0 ]; then
-                echo "Running ${file%.cpp}"
-                result=$(/usr/bin/time -v ./"${file%.cpp}" 2>&1)
-                echo "$result" > "${dir}/README.md"
+              if [ -f "$file" ]; then
+                dir=$(dirname "$file")
+                echo "Compiling $file"
+                g++ -o "${file%.cpp}" "$file"
+                if [ $? -eq 0 ]; then
+                  echo "Running ${file%.cpp}"
+                  result=$(/usr/bin/time -v ./"${file%.cpp}" 2>&1)
+                  echo "$result" > "${dir}/README.md"
+                else
+                  echo "Compilation failed for $file" > "${dir}/README.md"
+                fi
               else
-                echo "Compilation failed for $file" > "${dir}/README.md"
+                echo "No .cpp files found in $sheet/Submissions"
               fi
             done
+          else
+            echo "No Submissions folder found in $sheet"
           fi
         done
 
